#!/bin/bash

if [[ "$1" = "--help" ]] || [[ "$1" = "-h" ]]; then
cat <<EOF
Usage: tocode <file>
Executes: touch <file> && code <file> in current directory.

Author: Kyaw Zin Min
Version: 1.0
Created: 2025-12-07
Description:
       Combines touch & code cmds for quality of life.
EOF
exit 0
fi

file="$1"
touch $file && code $file